<?php

// DO NOT EDIT THIS FILE!!! Instead, copy and paste it and rename it to config.php (this one is just a sample)

$apiUrl = 'https://app-api-fk.niu.com';

// Read below on how to get the token and serialNumber
$token = '';
$serialNumber = '';

// To get your token and serial number, fill the userName and pass fields below, save the file and execute getToken.php
$userName = 'youremail@gmail.com';
$pass = 'yourpassword';

// Your scooter's battery original capcity in Wh; For N-GT it is 4200Wh
$batteryCapacityWh = 4200;

// Number of batteries your NIU has (2 for N-GT and NPro, 1 for the rest of models)
$batteryNumber = 2;

// Your desired charge level
$desiredChargeLevel = 60;

// Your desired charging finishing time
$endChargingTime = '7:30:00';

// Charging rate (minutes that it takes to charge an 1% of battery; for N-GT my readings are: 3.14516129 minutes per 1%)
$minutesPercent = 3.14516129;

// The current kWh price you're paying in your electricity bills
$kwhPrice = 0.12;

// Your currency
$currency = '€';